### ISSUE TITLE
Next bugfix release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10438]
After yesterdays release unfortunately more regressions showed up due to website changes.
So let me try to sort it out and list it here:
- [x] Login failure -> Issue #10434,  PR #10436
- [x] Owner ID -> Issue #10421 (remaining part) , PR #10430 
- [x] Watchlist feature -> Issue #10437 (might be related to owner ID?)
- [x] Relogin in the background -> Issue #10440

Lets try to use this issue to track what has to be done to be able to have another release.

**Comment by Lineflyer** [comment]
BTW:
In social networks there is quite some discussion, that also parts/features of the website are non functional at this moment (e.g. search map, bookmark lists, viewing of own unpublished caches, etc.). So the situation might still be evolving back or forth.

**Comment by Lineflyer** [comment]
PR #10436 and PR #10430 have been merged.
Will merge upstream and produce a new nightly for testing soon.

**Comment by Lineflyer** [comment]
New nightly is logging in fine and owner ID seems to work as well.
Strangely also the watchlist feature works again...maybe related to owner ID or fixed on server side.

Will do some more testing tonight and look into website stability or if further changes are occuring.
If its stable I will just push another release. I think its also good for Groundspeak to reduce failed login requests asap.

**Comment by Lineflyer** [comment]
The current state is not OK. Many network actions trigger a relogin behind the scenes. Will open an issue for that.

**Comment by Lineflyer** [comment]
Blocking issue added above!!

**Comment by Lineflyer** [comment]
Quite something going on on our support mailbox :(

![image](https://user-images.githubusercontent.com/949669/115766729-9552d900-a3a8-11eb-905c-83d93a049270.png)

**Comment by Lineflyer** [comment]
PR #10443 merged to `release` and upstream to `master`.
Nightly 2021.04.22-NB2 building right now.

Will test #10440 via developer build based on `release` and take a look at the network communication in log (relogins).

**Comment by Lineflyer** [comment]
Test result is in #10440 
We are not yet where we want to be. Any help for #10440 appreciated from someone with knowledge of these code parts.

**Comment by Lineflyer** [comment]
Thanks to #10450 we seem to be back in the game:
- Login problem is solved.
- Repeated relogin attempts are solved
- Smoke test seems ok right now

Remaining regression is some owner identification problem for unknown/unsaved caches. However in most cases it works, therefore I do consider this rather minor. Getting the app back to work has more priority than this regression, which I would (at this moment looking at it) consider minor.

Will prepare a release to save the weekend for our fellow users.

**Comment by Lineflyer** [comment]
- [x] Check/Insert correct version name as headline in ```changelog-release.xml``` 
- [x] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid 
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment]
Release 2021.04.24 is processed by Google Play.
Keep fingers crossed for a nice caching weekend.

**Comment by balu2003** [comment]
You all  have done a great job. I have downloaded the Release 2021.04.24 from github an installed it on my "old" Galaxy S7.
Login is possible and everything seems work fine: :-)

**Comment by moving-bits** [comment]
> Release 2021.04.24 is processed by Google Play.
> Keep fingers crossed for a nice caching weekend.

Thanks for testing and for preparing the release. Let's hope everything stays calm and will continue to work, no more website changes hopefully...
