### ISSUE TITLE
Use separate waypoint type for generated waypoints

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12626]
### Tell us your idea!

A follow-up to #12384/#12588, as discussed briefly in https://github.com/cgeo/cgeo/pull/12505#issuecomment-1008110945:

Use a separate waypoint type for the generated waypoints, which would allow for both
- using a separate icon for those waypoints (to detect them more easily on the map),
- a function to "delete all generated waypoints" on the waypoints tab.

### What solution would you suggest?

- use a separate waypoint type for generated waypoints
- implement a new icon for this waypoint type
- add a function "delete all generated waypoints" to the waypoints tab

[Edit]
### TODO List
- [x] Create separate waypoint type with icon and compact mode icon - #12693
- [x] Add item to cache details to remove all generated waypoints - #12734
- [ ] Store reference to originating waypoint for all generated waypoints
- [ ] Add item to waypoint popup for generated waypoints "delete all from this series"
- [ ] Add item to waypoint popup for originating waypoints "delete all from this series"
- [ ] Add button "delete all generated for this waypoint" to calculate dialog above "generate range items"

**Comment by moving-bits** [comment]
I could start working on the technical aspects of this issue, but this would only make sense if someone implements a new drawable.

@ztNFny 
Would you be willing to create a drawable for this new waypoint type?

**Comment by ztNFny** [comment]
> Would you be willing to create a drawable for this new waypoint type?

Can do. How about the icon currently used to mark a wp as calculated? The 4 icons

**Comment by eddiemuc** [comment]
The challenge with this issue is IMHO not so much the introduction of a new waypoint type (this is actually very easy) but to come up with a good UI concept to allow easier editing (or in this case: "mass-deletion") of selected waypoints (in this case: all wps of a specific type)

**Comment by Lineflyer** [comment]
If such new type is introduced, would I still be able to use one of the other types for such a calculated waypoint?

Because I would not like to lose the possibility to define those as "Stage", "Trailhead", "Final" as required by the cache.

**Comment by ztNFny** [comment]
What would be the concept for this new waypoint type? I sometimes use "coordinate joker" with Locus which adds possible locations to the map with their own icon - for that it'd be useful.
Today I did a multi with the new calculator, set up a waypoint of type final with the formula from listing. For that one I do not want to have some new waypoint type but it must be final - because that's what it is.

**Comment by eddiemuc** [comment]
For clarification: with the new calculated coordinates I recently introduced the possibility to generate waypoints from variable ranges. See #12588 for a detailled description how it works. the waypoints are generated out of a calculated coordinate, but they have themself fixed coordinates once they are created.

As of now, these generated waypoints will always have type "Reference Point" (as can be seen in screenshots in the PR referenced above), this is hardcoded.

The idea behind this issue is to introduce a new waypoint type for exactly those generated waypoints. Nothing else shall change. If these waypoints have their own type they can easily be identified as generated, also in a second step a "delete all generated waypoints" function might be added to waypoint list (because those generated waypoints tend to be useful only temporary, and it is easy to generate a lot of them at once).

@moving-bits at least this was my understanding, is this correct?

**Comment by ztNFny** [comment]
> The idea behind this issue is to introduce a new waypoint type for exactly those generated waypoints.

That'd match "coordinate joker" and would be 100% ok for me

**Comment by ztNFny** [comment]
some quick icon ideas:
![image](https://user-images.githubusercontent.com/1258173/152654485-7fbb2294-fc92-465c-9e6c-d7cd1f91be0f.png)
inner part of
![image](https://user-images.githubusercontent.com/1258173/152654520-7f33c6f2-d70b-4801-8b6a-3fdced906172.png)
![image](https://user-images.githubusercontent.com/1258173/152654607-c07031bd-8c3e-420f-bb76-b93311cdd5e8.png)

**Comment by Lineflyer** [comment]
> The idea behind this issue is to introduce a new waypoint type for exactly those generated waypoints. 

Ah ok, perfect.

**Comment by Lineflyer** [comment]
![image](https://user-images.githubusercontent.com/1258173/152654520-7f33c6f2-d70b-4801-8b6a-3fdced906172.png)

That would actually match, what is also used for a "non joker" calculated waypoint as marking in the waypoint list. Therefore I think it would be consistent to reuse it for this "joker" type.

**Comment by eddiemuc** [comment]
> ![image](https://user-images.githubusercontent.com/1258173/152654520-7f33c6f2-d70b-4801-8b6a-3fdced906172.png)
> 
> That would actually match, what is also used for a "non joker" calculated waypoint as marking in the waypoint list. Therefore I think it would be consistent to reuse it for this "joker" type.

Actually, the other symbol suggested by @ztNFny is used these days:

![image](https://user-images.githubusercontent.com/6909759/152656361-d97bd43a-e0c7-4601-afb0-c407c105c75b.png)

**Comment by moving-bits** [comment]
> If such new type is introduced, would I still be able to use one of the other types for such a calculated waypoint?
> 
> Because I would not like to lose the possibility to define those as "Stage", "Trailhead", "Final" as required by the cache.

see @eddiemuc's answer - all those generated waypoints are of type "reference" today, you cannot select an individual type as of now.

> For that one I do not want to have some new waypoint type but it must be final - because that's what it is.

IMHO the generated waypoints are more a sort of "possible finals" - that's why I would like to have a separate waypoint type for.

> The idea behind this issue is to introduce a new waypoint type for exactly those generated waypoints. Nothing else shall change. If these waypoints have their own type they can easily be identified as generated, also in a second step a "delete all generated waypoints" function might be added to waypoint list (because those generated waypoints tend to be useful only temporary, and it is easy to generate a lot of them at once).
> 
> @moving-bits at least this was my understanding, is this correct?

exactly - easy to identify on the map, and easy to delete after the right one has been found in real life.

To set one of those generated waypoints as final, you would copy the generated waypoint and change its type to "final".

**Comment by moving-bits** [comment]
> That would actually match, what is also used for a "non joker" calculated waypoint as marking in the waypoint list. Therefore I think it would be consistent to reuse it for this "joker" type.

Just to avoid a possible misunderstanding: This issue is about creating a new waypoint symbol to be shown on the map, not about a symbol being displayed additionally in waypoint list. So, taking the screenshot in https://github.com/cgeo/cgeo/issues/12626#issuecomment-1030686805 as reference, the new symbol would replace the white circle with the red circles in it, not the "_(x)_".

**Comment by moving-bits** [comment]
> The challenge with this issue is IMHO not so much the introduction of a new waypoint type (this is actually very easy) but to come up with a good UI concept to allow easier editing (or in this case: "mass-deletion") of selected waypoints (in this case: all wps of a specific type)

Have a few ideas for this:

As you can already delete single generated waypoints, the only missing feature is "mass-deletion" of _all_ generated waypoints. To make things a bit more comfortable, you could distinguish between "all from this cache" and "all from a specific originating waypoint", which leads to the following possible solutions:

- Add a button "Delete generated coordinates for this waypoint" above the "Generate range coordinates" button
  - => would delete all waypoints which have been generated for this waypoint only
  - could also be an option for the long-press menu for the original waypoint
- Optionally add a "Delete all from this series" to the long-press menu for any generated waypoint
  - would delete all generated waypoints having the same lookup code (= original waypoint's internal id) as the selected one
- Add "Remove all generated waypoints" to the waypoints list's "waypoint" menu
  - would remove all generated waypoints from this cache, regardless of their originating waypoints
- To be able to detect a relationship between an originating waypoint and the generated waypoints generated from it, you could store the originating waypoint's internal id in the "lookup" column of each waypoint generated from it.

**Comment by moving-bits** [comment]
based on material.io:calculate: (as shown above)

![image](https://user-images.githubusercontent.com/3754370/152682502-23fe6db0-01ac-4b00-95fe-6f1ca45f1b79.png)

**Comment by ztNFny** [comment]
hm, I find that one way too busy in the marker. Also transparency in the icon color is not nice.
But I'd suggest you commit whatever you have in terms of icon and then I'll take a look at tuning that?

**Comment by eddiemuc** [comment]
@moving-bits keep in mind that at least now there's no relationship between "origin waypoint" and "generated waypoints" kept in db or elsewhere. Also, origin waypoint may be deleted or changed (eg to a "normal" noncalculated waypoint) after generationm also, Multiple generations can be done from same waypoint.

**Comment by moving-bits** [comment]
> hm, I find that one way too busy in the marker. Also transparency in the icon color is not nice. But I'd suggest you commit whatever you have in terms of icon and then I'll take a look at tuning that?

Feel free to create a more consistent one. So far I've only taken the material.io icon suggested above, adjusted sizes/positions, and dimmed down the color a bit. But I'm no SVG / Android drawable expert...

**Comment by moving-bits** [comment]
> @moving-bits keep in mind that at least now there's no relationship between "origin waypoint" and "generated waypoints" kept in db or elsewhere. 

I know, that's why I suggest to introduce such a relationship by using the "lookup" column in the generated waypoints. They could either hold the internal id of the originating waypoint or their lookup code, if the latter is cache-unique.

> Also, origin waypoint may be deleted or changed (eg to a "normal" noncalculated waypoint) after generationm also,

That would not lead to a problem. If we introduce the "delete from series" action to the long-click menu, you will still be able to delete the whole series.

> Multiple generations can be done from same waypoint.

Yes, stumbled upon that already ;-) If you generate multiple times with the same parameters, you get a couple of identical waypoints...
I did not intend to introduce some magic here. If one would like to delete generated waypoints from an earlier run, you can use the proposed button "Delete generated coordinates for this waypoint" (or however we decide to label it). Otherwise they are kept. No automatic deletion of existing generated buttons intended when pressing the "Generate range coordinates" button.

**Comment by ztNFny** [comment]
I tried to test this to create the icons but couldn't figure out how to define a variable so that it inserts a range. Any help please?

**Comment by eddiemuc** [comment]
> I tried to test this to create the icons but couldn't figure out how to define a variable so that it inserts a range. Any help please?
> 
> edit: nvm, found it

I think I haven't updated the wiki page yet. Will do so.

**Comment by eddiemuc** [comment]
Range values are now documented here: https://github.com/cgeo/cgeo/wiki/Calculator-Formula-Syntax

**Comment by eddiemuc** [comment]
> @eddiemuc - I was paying with coordinate calculator and bemoaning the lack of up to date documentation when I came across this ticket - more specifically your last comment.  When I try open that link Wiki invites me to create a new page!   Does it exist somewhere ?
> Tks

Yes, seems to be outdated. Can't find it too, son probably deleted (maybe because info is now inside user manual)

**Comment by ReggieDoodle** [comment]
I couldn’t find it anywhere in the manual.  I’ve managed to work out how to use it from the error message it pops up if I don’t have the right format 😉

**Comment by ztNFny** [comment]
https://manual.cgeo.org/en/cachevariables#range_expressions

**Comment by murggel** [comment]
@eddiemuc  can we close here?

**Comment by eddiemuc** [comment]
> @eddiemuc  can we close here?

Think so
