### ISSUE TITLE
Next feature release

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#12857]
In yesterday's dev call we decided time for a new beta is coming closer. If no one objects (and nothing too bad happens on support), we should create a new `release` branch from `master` later this week.

So let's collect things that need to be done before beta and/or before the next feature release. Feel free to edit those lists:

## Things to be done before next beta release
- [x] #12813
- [x]  #12856
- [x] #12755 (added a reproducible case)
- [x] #12889 (as this function is rather important and the fix is easy it should be included)

## Things to be included additionally for next feature release
- [x] #12852
- [x] bottom margin for quick launch buttons, see https://github.com/cgeo/cgeo/pull/12817#issuecomment-1066425651, see #12858

**Comment by Lineflyer** [comment]
I added #12755 above as I now found a clue about the cause and a reproducible scenario

**Comment by fm-sys** [comment]
Which "big new features" will come with the release? When reading the changelog, it actually looks more like a normal bugfix release. Still, that won't block us from releasing :) 

Side note: Have you discussed whether the filtering is ready to be switched on?

**Comment by fm-sys** [comment]
Which "big new features" will come with the release? When reading the changelog, it actually looks more like a normal bugfix release. Still, that won't block us from releasing :) 

Side note: Have you discussed whether the new calculator is ready to be switched on?

**Comment by moving-bits** [comment]
We also have
- variables tab, global variables etc.
- new image tab

as exciting new features.

Though I'm not sure whether this is intended to replace today's functionality with the upcoming beta already, and how much would have to be done yet before being able to release.

**Comment by eddiemuc** [comment]
> * new image tab

This is far from being release/beta-ready I am afraid. Probably has to wait until next round

**Comment by moving-bits** [comment]
> > * new image tab
> 
> This is far from being release/beta-ready I am afraid. Probably has to wait until next round

No worries, we still like to have cool new things for the next upcoming feature release :-) 

But what about variables & new calculator - ready to replace today's functionality? (Not sure whether it's still bound to dev builds to be visible or already available globally.)

**Comment by eddiemuc** [comment]
> what about variables & new calculator - ready to replace today's functionality?

Oh, this is set up on master for quite a while now. It is no longer restricted to dev/nightly builds and should become part of next beta

**Comment by moving-bits** [comment]
> Oh, this is set up on master for quite a while now. It is no longer restricted to dev/nightly builds and should become part of next beta

Great news! Can you provide a feature description for `changelog_base.md`?

**Comment by eddiemuc** [comment]
> > Oh, this is set up on master for quite a while now. It is no longer restricted to dev/nightly builds and should become part of next beta
> 
> Great news! Can you provide a feature description for `changelog_base.md`? 
> 
> 

Hm, maybe:
* New: Calculate waypoint coordinates using global cache variables

Or:
* Update: Variables for waypoint calculation are now cache-global

**Comment by moving-bits** [comment]
IIRC the whole coordinate calculator is new, so maybe something like:
- New: New coordinates calculator (supporting formulas)
- Change: Variables for waypoint calculation are now cache-global
- New: Variables tab in cache details

?

**Comment by eddiemuc** [comment]
> IIRC the whole coordinate calculator is new, so maybe something like:
> - New: New coordinates calculator (supporting formulas)
> - Change: Variables for waypoint calculation are now cache-global
> - New: Variables tab in cache details
> 
> ?

Second and third are ok, but the first one is not really true. There already is a coordinate calculator supporting formulas in c:geo, the fact that I reimplemented that part too does not change this from a users perspective. Maybe use "redesigned" instead of "new"?

**Comment by wolverine007** [comment]
What about the long-press function which has been added to the Search button to open a list of recently viewed caches?

Working without any issues inside the nightly for several weeks now.

**Comment by Lineflyer** [comment]
> What about the long-press function which has been added to the Search button to open a list of recently viewed caches?
> 
> Working without any issues inside the nightly for several weeks now.

If its included in the nightlies it will be included in the next feature release "automatically" as we branch this off from `master`.

**Comment by Lineflyer** [comment]
Any idea about the three open issues identified in the first post, whether someone is working on that?

**Comment by fm-sys** [comment]
These three bugs aren't newly introduced ones AFAIK, so I guess they could be fixed during the beta or even in a separate bugfix release as well...

**Comment by moving-bits** [comment]
I've prepared a PR for #12889

**Comment by moving-bits** [comment]
As nobody seems to be working on the two remaining issues currently (and they probably already exist in current release according to https://github.com/cgeo/cgeo/issues/12857#issuecomment-1112540472) I propose to start a new beta cycle based on current state of `master`. If no one objects I'll start working on this tonight.

**Comment by eddiemuc** [comment]
@moving-bits would it be ok to merge https://github.com/cgeo/cgeo/pull/12948 before doing the beta release? I would really really ned this in production soon...

**Comment by eddiemuc** [comment]
Provided possible fix for #12755

**Comment by moving-bits** [comment]
> @moving-bits would it be ok to merge #12948 before doing the beta release? I would really really ned this in production soon...

Sure, LGTM.

What about #12883? The screenshots you have provided look very promising, and normally I would have said let's include it to have the possibility to release it with the upcoming release as well, but after having read your comments in https://github.com/cgeo/cgeo/issues/12783#issuecomment-1114257637 I'm unsure whether you want to see this included as well...

**Comment by moving-bits** [comment]
Starting beta cycle soon (depending on whether to include #12883 with it), following the usual steps:

- [ ] prepare changelogs (move yet unused contents of `changelog_bugfix.md` to `changelog_base.md` and "empty" `changelog_bugfix.md` after that)
- [ ] fast-forward release branch to the head of master
- [ ] Check/Import incoming Translations from Crowdin
- [ ] For an upcoming full release, check/insert correct version name in ```/main/src/cgeo/geocaching/utils/BranchDetectionHelper.java```  (using format `YYYY.MM.DD-RC`), for a beta bugfix release.
- [ ] Build release on [CI server](https://ci.cgeo.org/job/cgeo%20release%20candidate/) (Download available after build from [here](https://download.cgeo.org/cgeo-RC.apk))
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play (Channel/Release type: open test) (Account required for the c:geo team Google Play account)
- [ ] Trigger notification to status.cgeo.org via [CI server](https://ci.cgeo.org/view/Notification%20system/job/Create%20release%20notification/) once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day)

**Comment by eddiemuc** [comment]
> What about #12883? The screenshots you have provided look very promising, and normally I would have said let's include it to have the possibility to release it with the upcoming release as well, but after having read your comments in [#12783 (comment)](https://github.com/cgeo/cgeo/issues/12783#issuecomment-1114257637) I'm unsure whether you want to see this included as well...

I just merged it. There are two aspects I want to pursue:
* The optics and handling of the viewer. This is the main reason I want this in master now  - to get feedback and to be able to discuss 
* The used library for image handling. As of now it is Loupe. But if we decide later to switch to something else the place to do this is very isolated in code. So this can be done later

**Comment by moving-bits** [comment]
@bekuno @mucek4 @Lineflyer 

Release build fails with the same error as mentioned in https://github.com/cgeo/cgeo/pull/12825#issuecomment-1114201093:

```
20:31:40  * What went wrong:
20:31:40  A problem occurred configuring root project 'cgeo'.
20:31:40  > Could not resolve all files for configuration ':classpath'.
20:31:40     > Could not resolve se.ascp.gradle:gradle-versions-filter:0.1.10.
20:31:40       Required by:
20:31:40           project : > se.ascp.gradle.gradle-versions-filter:se.ascp.gradle.gradle-versions-filter.gradle.plugin:0.1.10
20:31:40        > No matching variant of se.ascp.gradle:gradle-versions-filter:0.1.10 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.3.3' but:
20:31:40            - Variant 'apiElements' capability se.ascp.gradle:gradle-versions-filter:0.1.10 declares a library, packaged as a jar, and its dependencies declared externally:
20:31:40                - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
20:31:40                - Other compatible attribute:
20:31:40                    - Doesn't say anything about org.gradle.plugin.api-version (required '7.3.3')
20:31:40            - Variant 'runtimeElements' capability se.ascp.gradle:gradle-versions-filter:0.1.10 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
20:31:40                - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
20:31:40                - Other compatible attribute:
20:31:40                    - Doesn't say anything about org.gradle.plugin.api-version (required '7.3.3')
```
PR builds do work, though. 🤔 

Any idea on how to solve this?

**Comment by Lineflyer** [comment]
Do we need to remove any logging for production?

I noticed that c:geo produces quite many Info logs recently on normal usage. Not sure if this does any harm with respect to CPU time, etc.

**Comment by Lineflyer** [comment]
> Any idea on how to solve this?

Never seen such error before. No idea :(

**Comment by moving-bits** [comment]
> > Any idea on how to solve this?
> 
> Never seen such error before. No idea :(

See https://github.com/cgeo/cgeo/pull/12825#issuecomment-1114307559
I'm trying to contact @mucek4 for an upgrade of CI.

**Comment by moving-bits** [comment]
> Do we need to remove any logging for production?

not that I'm aware of

> I noticed that c:geo produces quite many Info logs recently on normal usage. Not sure if this does any harm with respect to CPU time, etc.

Depends on your logging settings (activated debug mode and `log.properties` in `logfiles` folder).

**Comment by moving-bits** [comment]
>  I'm trying to contact @mucek4 for an upgrade of CI.

Ok, updating CI will take a bit due to vacation. I see several approaches:
- wait a couple of days (or more) until CI is updated
- revert #12825 as this seems to be the PR requiring our builds to use Java 11

**Comment by eddiemuc** [comment]
> > I'm trying to contact @mucek4 for an upgrade of CI.
> 
> Ok, updating CI will take a bit due to vacation. I see several approaches:
> 
> * wait a couple of days (or more) until CI is updated
> * revert [use gradle-versions-filter #12825](https://github.com/cgeo/cgeo/pull/12825) as this seems to be the PR requiring our builds to use Java 11

Using an older version of the filter (0.1.8 instead of 0.1.10) seems to work. I created PR #12953 for it

**Comment by moving-bits** [comment]
> Using an older version of the filter (0.1.8 instead of 0.1.10) seems to work. I created PR #12953 for it

Thanks. Can you target this to `release` as I've already merged branches and updates changelogs and version file on `release`?

**Comment by eddiemuc** [comment]
> > Using an older version of the filter (0.1.8 instead of 0.1.10) seems to work. I created PR #12953 for it
> 
> Thanks. Can you target this to `release` as I've already merged branches and updates changelogs and version file on `release`?

Done

**Comment by moving-bits** [comment]
Thanks. And have a good night :-)

**Comment by bekuno** [comment]
@eddiemuc @moving-bits 
Thanks for fixing that problem based on my PR.

**Comment by moving-bits** [comment]
After some (successful) fight with Crowdin :-) our new beta version is uploaded to Play Store and should be available to beta users soon. Thanks to @cgeo/team and all other contributors for working on this version!

**Comment by alan666notb** [comment]
Will this beta have the fix for #12848 in it?

**Comment by nmrsmn** [comment]
How can I test the beta version?

**Comment by Lineflyer** [comment]
See https://www.cgeo.org/development for the link to join the Google Play beta program for c:geo.

**Comment by Lineflyer** [comment]
One question (as I did not follow all dev updates last days):
What is the state of the new image tab (pictures+) in the current beta version?
Did you consider it ready (=its visible) or still hidden in production?

**Comment by eddiemuc** [comment]
> One question (as I did not follow all dev updates last days):
> What is the state of the new image tab (pictures+) in the current beta version?
> Did you consider it ready (=its visible) or still hidden in production?

It is invisible in beta and prod. I wanted to use this weekend's dev meeting to gather a group opinion on how to proceed and what need to be adapted in the view to be production ready.

**Comment by Lineflyer** [comment]
As discussed in todays dev-meeting:

We will once more fast-forward `release` to HEAD of `master` to allow a clean code-formatting approach:
- [ ] Merge all PRs, which are ready to merge and "needed" for the upcoming release
- [ ] (Rebase) and merge the code formatting PR #12983 
- [ ] Check new code formatting
- [ ] Forward `release` to `master`
- [ ] Release a new RC version
- [ ] Merge other PRs foreseen for next release after current beta/release (e.g. dependency update which are mergeable)

Feel free to tick the above boxes once steps are completed or give me (or another team member) the Go! for branch merging.

**Comment by eddiemuc** [comment]
> We will once more fast-forward release to HEAD of master to allow a clean code-formatting approach:

If I understand correctly, then the only step left is to merge `master` into `release` - and not to do any PRs against release until this has happened (because this would result in huge merge conflicts when merging master into release). Correct?

**Comment by moving-bits** [comment]
I've added cross-checking the changelogs between `master` and `release`. Will do so tonight, and can prepare a new beta version as well.

**Comment by Lineflyer** [comment]
@moving-bits 
I leave the field up to you to check changelogs and do another merge.

**Comment by Lineflyer** [comment]
Shall we disable the geolutins test now on master, so that it will also be merged to `release`? Alternatively it could be done on `release` after the merge and then merged back into `master`. As you like...

**Comment by eddiemuc** [comment]
> Shall we disable the geolutins test now on master, so that it will also be merged to `release`? Alternatively it could be done on `release` after the merge and then merged back into `master`. As you like...

I already disabled the test as part of PR #12985 yesterday

**Comment by moving-bits** [comment]
Started preparing a new beta...

- [x] merge all relevant outstanding PR
- [x] check changelogs
- [x] forward branches
- [ ] Check/Import incoming Translations from Crowdin
- [x] For an upcoming full release, check/insert correct version name in ```/main/src/cgeo/geocaching/utils/BranchDetectionHelper.java```
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play (Channel/Release type: open test) (Account required for the c:geo team Google Play account)
- [ ] Trigger notification to status.cgeo.org via [CI server](https://ci.cgeo.org/view/Notification%20system/job/Create%20release%20notification/) once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day)

**Comment by Lineflyer** [comment]
Shall I prepare another round of beta before next weekend?

Changes compared to current beta are:
- NPEs fixed for cache variables
- New translations
- Changed activity stack

**Comment by eddiemuc** [comment]
Would it be possible to merge master to release before beta prep one more time? This would then allow to activate experimental image gallery also in beta/prod by setting a hidden property.

**Comment by Lineflyer** [comment]
We could do that.
We would then have additionally on beta:
- RX-Java update 
- New setting for hint encryption

which does not look critical.

But what would be the advantage?
No standard user will probably know/use the hidden property.

**Comment by eddiemuc** [comment]
> But what would be the advantage?
> No standard user will probably know/use the hidden property.

I will know :-) and probably activate it for my own installation.

Also it would give the possibility to include it in current beta as a complete feature in case beta runs for some weeks and we could close feature in this time. Modifications to make it available for all users would be trivial on release branch after current master would be merged to release now.

**Comment by Lineflyer** [comment]
OK.
What about #13005? Do you want to include it as well, then feel free to merge.

I will start merging branches at 1200 CEST.

- [ ] merge all relevant outstanding PR
- [ ] check changelogs
- [ ] forward branches
- [ ] For an upcoming full release, check/insert correct version name in ```/main/src/cgeo/geocaching/utils/BranchDetectionHelper.java```
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day)

**Comment by eddiemuc** [comment]
> What about #13005? Do you want to include it as well, then feel free to merge.

Is merged

**Comment by Lineflyer** [comment]
OK, then I will start now.

**Comment by Lineflyer** [comment]
Beta update 2022.05.13-RC derived from current `release` after forwarding `release` to `master` has been uploaded to Google Play.

**Comment by Lineflyer** [comment]
The current beta has already summed up >300 crashes for #13014, thus I would suggest to push another update including the fix.
However maybe someone could look at my latest comment to #12801 regarding working mode of this change, so that we could - if needed - improve the behavior.

**Comment by eddiemuc** [comment]
> The current beta has already summed up >300 crashes for #13014, 

If users can't wait for next beta, they may add manually a new boolean property `feature_new_image_gallery` with value `true`. This will activate the new image gallery in beta - the exception will vanish then.
But I would prefer if a new beta with the fix is shipped.

**Comment by Lineflyer** [comment]
> owever maybe someone could look at my latest comment to https://github.com/cgeo/cgeo/pull/12801 regarding working mode

That was the wrong..correct is #12821

**Comment by Lineflyer** [comment]
The follow-up problem for #12821 as well as #13014 have been solved.
I will prepare another (potentially final) round of beta today, if no one stops me.

**Comment by murggel** [comment]
I just found a crash on calculated waypoints with the new variable tab - will create an issue, I wasn't able to fix it 😔

**Comment by Lineflyer** [comment]
Next beta round not yet started as I was waiting for #13028 . Can this be merged = included for next beta?

**Comment by Lineflyer** [comment]
Done.
Lets kick in the next/last beta round after the weekend.

**Comment by moving-bits** [comment]
@Lineflyer
I propose to include #13034, #13035 and maybe #13037 in next beta as well. First one fixes a crash, second is the (small) extension for marking unknown caches as found, and the last one remove Geolutin.

**Comment by Lineflyer** [comment]
@cgeo/team Please kindly check out/merge the changes/PRs suggested above as time permits. Will continue with next beta after mergings/decisions are done.

**Comment by fm-sys** [comment]
I've now merged all PR's except the removal of Geolutin...

**Comment by Lineflyer** [comment]
> I've now merged all PR's except the removal of Geolutin...

Thanks!
Regarding Geolutins I am a bit undecided:
On one hand I can understand, that you want to wait. On the other hand the service is permanently unavailable for several weeks right now and codewise we could still revert the removal via Git in the next bugfix release.
What do others think?

**Comment by Lineflyer** [comment]
I merged the geolutin removal (see PR comments for reasoning). Also I updated the changelog_base and merged everything updtream.

Lets try tomorrows nightly and then push the next beta if all is fine.

**Comment by Lineflyer** [comment]
Nightly was working rather normal.
I will go for a next beta now unless I read some stopping item here next minutes.


- [ ] For an upcoming full release, check/insert correct version name in ```/main/src/cgeo/geocaching/utils/BranchDetectionHelper.java```
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-RC.apk``` before continuing
- [ ] Upload and publish ```cgeo-RC.apk``` to Google Play
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day)

**Comment by Lineflyer** [comment]
I would say:
Lets wait some more days for translations (recently variable strings have been added) and release a productive release after this weekend.
No critical issues on crash reports and user mails so far.

**Comment by moving-bits** [comment]
Will start building next release shortly...

- [ ] Check and merge open Crowdin translation pull requests for `release`
- [ ] For an upcoming full release, check/insert correct version name in ```/main/src/cgeo/geocaching/utils/BranchDetectionHelper.java```
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github in format `market_yyyymmdd`
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github 
- [ ] Publish release on F-Droid
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play (not just being processed, but being available for download - sometimes takes up to one day)
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by moving-bits** [comment]
Play Store has crunched our new version successfully, downloads are available. All set here (except notifications on FB/Twitter - @Lineflyer?).

Thanks to all the contributors for you dedicated work!

**Comment by Lineflyer** [comment]
Thanks @moving-bits !

I will post on FB / Twitter-
