### ISSUE TITLE
Next feature release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#2897]
We should not include any further big feature for the next release, but get the current new stuff finished and polished. Please add issues to this list directly, if you see them blocking the next release.

@Lineflyer added
- [x] #2122 Personal Note synchronization.
- [x] #2826 From my users/testers perspective I think needs to be solved as well (The problem, that on empty tiles for PM we are still showing them if retrieved on lower zoom)
- [x] What about #2821 which came in probably after the new basic member nearby search implementation?

@Bananeweizen added:
- [x] #2898 
- [ ] #2770 
- [x] #2443 
- [x] #2747 

@Lineflyer added:
- [x] #2925
- [x] #2926
- [x] #2932 
- [x] #3000 
- [x] #2996
- [x] #2606 
- [x] #3086 
- [x] #3104
- [x]  #3111 
- [ ] #3136

@samueltardieu added:
- [x] #2915 A release from the `release` branch with the end-of-line warning must be done first
