### ISSUE TITLE
Next bugfix release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5403]
Just a small collection of issues already discussed to be solved with an possible next bugfix release after 2016.01.19:

- [ ]  Refresh all warning also for low amount of caches on list or selected caches #5400 *in field test on master*
- [x]  MissingBackpressureException #5402 *in field test on master*
- [x] Storing some caches from search result lead to a "refresh all" popup #5396 
- [x]  Number of caches on PQ selection dialog meaningless #5391 
- [x] Crash in PocketQueryListActivity on Android 2.3.x #5408 
- [x] Crash in ECLogin due to Improper check of credentials #5409

Not to forget possible fixes for this:
 Prepare for site change - Markdown for logs #5379

**Comment by kumy** [comment]
#5396 is closed

**Comment by Lineflyer** [comment]
#5402 merged into release. closed here.

**Comment by Lineflyer** [comment]
Some fixes have been released with 2016.02.03. Therefore closing here, adapting the milestones and opening a new issue.
