### ISSUE TITLE
Next feature release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5446]
ToDo for a possible next bugfix release:

- [x]  #5400 Refresh all warning also for low amount of caches on list or selected caches 
-  [ ]  #5327  List not refreshed after importing GPX/PQ
- [x] #5490 Scrolling broken
- [x] #5491 Line feeds missing for own logs in logbook 
- [x] #5497 Problems with nearby sorting
- [x] #5499 Problem with google gms analytics provider

**Comment by Lineflyer** [comment]
Added  #5327

**Comment by kumy** [comment]
#5400 merged on Mon Feb 15 (f5d8d08)

**Comment by Lineflyer** [comment]
Updated title as we are now going for a feature release.
Added some of the findings during RC-testing which I consider a significant regression.

**Comment by kumy** [comment]
Ack of #5491

**Comment by Lineflyer** [comment]
noack of #5491 ;)

**Comment by rsudev** [comment]
Added #5497 and #5499

**Comment by rsudev** [comment]
Closed #5499 (487e4f0)

**Comment by rsudev** [comment]
#5497 closed by (64efde4)

**Comment by Lineflyer** [comment]
Currently we have three issues left. 
Is someone able to tackle them in due time? 
From my perspective the `release` branch is stable and all basic functions OK, from the three issues listed above I do only think that #5490 is a strong regression. The others could be solved also with another bugfix release later on.
My concern is, that I don't want to let too much time before releasing as also `master` changes rapidly and may need more testing focus.

**Comment by Bananeweizen** [comment]
I have the same feeling that the scrolling needs to be fixed, the others can be done later, as there are simple workarounds in both cases.

**Comment by Lineflyer** [comment]
Marked #5490 as solved, marked #5491 as done as no longer reproducible.

**Comment by Lineflyer** [comment]
As no one objected until now and the above mentioned critical issue is solved, I suggest to start a staged release this evening. 
I will prepare the needed things...let me know here or on IRC is there is a problem with that.

BTW:
What about #5490: For me its tested OK...but I did not follow the workaround/fix you did. Are we sure it behaves alike on all devices?

**Comment by Lineflyer** [comment]
As there was no objections: 
Release 2016.03.06 pushed out to 20% of users.
Please kindly keep an eye on Play Store crashes, etc.

**Comment by Lineflyer** [comment]
@samueltardieu or someone else:
Could you tag the release 20160306 at 60775e80f41a053ad885631fb8de4e05848e2d35

**Comment by samueltardieu** [comment]
Done.

**Comment by rsudev** [comment]
There are two crashes in Play, likely from the same person (device HTC ONE M8s, Android 5.0), dutch comment. But this is now new issue (likely an installation problem).
Nothing else so far.

**Comment by Lineflyer** [comment]
Release set to 100% on Play.
Remaining issue from this list will be taken to "Next bugfix release".
