### ISSUE TITLE
Next bugfix release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5901]
Issues to be solved for the next bugfix release after 2016.08.14 feature release:

- [x] #5910: java.lang.IllegalArgumentException: credentials are not valid in Credentials.guard
- [ ] #3528 : Longer existing NPW which now shows up more frequently 
- [x] #5916: Intworking with newest maps.me not working
- [x] #5913: NPE/Illegal State Exception

**Comment by kumy** [comment]
Added #5910

**Comment by Lineflyer** [comment]
I added three more ToDo which seem relevant/significant from my perspective:
- Maps.me problem 
- Two crashes which occur rather frequently on GooglePlay

**Comment by Lineflyer** [comment]
Based on Play Store comments and support mail there seem to be three large areas of concern for our users after the feature release:

- Maps.me problem --> Shows up to be a maps.me problem. Probably nothing we can do?!
- Crash in Settings ---> Most likely fixed already on `release` branch
- ANR and Crashes on Map --> Here it is unclear for me, whether this is already included in the topics listed above or not. This would be a real urgent point as a lot of users complain that stability dropped significantly. Does someone have an idea on this??

**Comment by rsudev** [comment]
I am right now cross-checking Play. For everything besides the maps.me issue which is listed here I have created PRs. I can merge those to put out another beta.

**Comment by Lineflyer** [comment]
As I think we need a rather quick way forward and those issues are hardly testable by myself, I agree to put these fixes on `release` branch and have a broader test via beta.
@rsudev: Feel free to do as proposed from my point of view.
@samueltardieu By the way: You might need to check the notification system. It seems to be stuck in the RC-deployment as the RC notification is not working (I created an issue for that).

**Comment by Lineflyer** [comment]
After chat on IRC changes have been made on `release` and a corresponding RC 2016.08.25-RC pushed to Google Play Beta channel.

**Comment by Lineflyer** [comment]
Anyone with on opinion whether we should release the current beta? Not much time since we published the beta... I used it myself and it is working normal for now. IMHO things can only get better with the update.

**Comment by Lineflyer** [comment]
I will build a release and publish based on best knowledge and test results (for me OK, no critical feedback on beta channel). 

- [ ] Publish release on Google Play
- [ ] Rework milestones on Github
- [ ] Tag release on Github
- [ ] Push notification as soon as available
- [ ] Post to social networks

**Comment by Lineflyer** [comment]
@rsudev Do you think #3528 should be solved as well (it is listed above)

**Comment by rsudev** [comment]
No, #3528 is not yet addressed.

**Comment by rsudev** [comment]
I have yesterday evening done some analysis on the crashes on play.

In the last week we had (according to play) 57 different crashes with together 193 occurences.
The largest group is associated with network problems WRT geocaching.com. 62 crashes can be attributed to this in different forms (connection timeout, ssl handshake failures, host not found). A small group of these (9 occurences) are native crashes in the openssl library, the remainder are crashes in Java - and it totally evades me how these can crash c:geo, as we expect and handle these (I could see this on my phone at least!).
63 of the crashes would have been prevented by the fixes we just released.
The remaining ones are distributed among various reasons. The single largest group are 11 crashes related to #3528. Some of the others we likely can address, others I have no clue at all.

**Comment by Lineflyer** [comment]
@pstorch I have seen you asked on IRC if there are urgent tasks. Do you have access to the c:geo Google Play Console (crash reports, etc.)?
It might be helpful if more people crosscheck the crash reports there....if you want.
If you don't have access I think @mucek4 needs to enable your gmail account for it.

**Comment by Lineflyer** [comment]
All things done here. Closing.

**Comment by pstorch** [comment]
@Lineflyer I don't have access to the Google Play Console, yet.
