### ISSUE TITLE
Next bugfix release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7069]
While the new feature release 2018.06.26 is just out I open this issue to track the regressions we did not manage to solve:
- [ ] #5885 - Circles feature missing on new map
- [ ] #5900 - Waypoints not always shown on new map
- [ ] #5902 - Nearby result not updated to new map

Furthermore there are issues, regressions reported just after release:
- [x] #7068 - Only 20 trackables shown on logging page

These listed issues could/should be the main target to be solved for the next bugfix release.

**Comment by Lineflyer** [comment]
Although not all of the above issues are solved, we could rather soon release a bugfix version.
Additionally to #7068 mentioned above, also #7049 was fixed and we modified the donation link.

There is one parsing issue since yesterday regarding personal note parsing (#7101). Once we solved this, I suggest to release.

Meanwhile it would be good if someone can (first merge release into master to catch up) and upload strings to Crowdin to get translation for the change donation strings.

**Comment by Lineflyer** [comment]
Crowdin translations done, thanks to @pstorch 
I will produce a RC version. Will have no time on the weekend, but then we can at least see how the RC performs.

**Comment by Lineflyer** [comment]
2018.08.09-RC smoke tested and uploaded to beta channel.

**Comment by Lineflyer** [comment]
RC-version does not show anything critical in PlayConsole.
Any objections to release today? Else I will do that in the afternoon/evening.

**Comment by Lineflyer** [comment]
Going for releasing now 2018.08.13 now:


- [x] Check/Import incoming Translations from Crowdin
- [x] Check/Insert correct version name as headline in ```changelog-release.xml```
- [x] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid 
- [ ] Rename/Create milestones on Github
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to G+ 
- [ ] Post release info to Twitter (via @SammysHP)

**Comment by Lineflyer** [comment]
All release tasks are done. Version 2018.08.13 is out.
