### ISSUE TITLE
Next feature release

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8041]
As discussed in #8030 after the new bugfix release we should merge branches to beta test the map autorotation besides other changes.

Current state as of 2020-02-19 is:

Included on release branch are the following PR:
- [x] #8033 (Implements #7196)
- [x] #8034 (Fix for #7949)
- [x] #8038 (Fix for #8037)
- [x] #8046 (Fix for #8040)
- [x] #8053 (Fix for #8049)
- [x] #8063 (migration of up to 5 targets of "go to" history)
- [x] #8071 (fix for #8042 / #8067)
- [x] #8070 (fix for #8069)
- [x] #8072 (fix for #8068)
- [x] #8088 (fix for #8082, part 1)
- [x] #8095 (fix for #8082, part 2)
- [x] #8099 (fix for #8082, part 3)
- [x] #8098 (workaround for #8097)
- [x] #8113 (fix for #8096 and #8111)
- [x] #8118 (finetuning migration order of goto history elements)
- [x] #8124 (fix for #8123)
- [x] #8127 (fix for cache map zoom)

The following PR, already targeted for release branch, should be included as well:
- /

Also fix(es) for the following issue(s) should be included IMHO:
- /

Feel free to add other ToDo items before merging branches.

**Comment by moving-bits** [comment]
We also need to decide whether we want to migrate current "go to" targets or not.

- pro: targets and history stay available
- con: possible pollution through too many waypoints

Proposal: Either do not migrate any "go to" targets (but inform the user upfront), or migrate the last five or ten targets.

Additional info: So far the code for replacing the "go to" function does not delete the database table where the "go to" targets currently are saved to, so we still do have some time to decide how to proceed.

**Comment by bekuno** [comment]
I would implement a solution for #7998, but its not ready.

**Comment by Lineflyer** [comment]
Lets just wait some time and see when it might be the right time to merge branches. IMHO #7998 is not so critical.

**Comment by Lineflyer** [comment]
Regarding the Goto targets:

IMHO only very few users use the current "Go to". If those using it also use the history....no idea. 
However the clean solution would be to migrate 5-10 history items, but not more.

BTW:
Should the "Go to" UDC be shown in any list. I still do not see this user defined caches list, which AFAIR should be created for them...

**Comment by Lineflyer** [comment]
> I would implement a solution for #7998, but its not ready.

That would go to release branch anyway, so it does not depend on branch merging (you then only need to rebase your change accordingly).

**Comment by moving-bits** [comment]
> Should the "Go to" UDC be shown in any list. I still do not see this user defined caches list, which AFAIR should be created for them...

No, there is no separate (visible) list just for UDC. The "go to" UDC is only shown in "All Caches" virtual list, and all other UDC are handled just like any other cache - they are either stored to the currently active list (if available) or to standard list, and may be moved around later if needed.

**Comment by moving-bits** [comment]
> IMHO only very few users use the current "Go to". If those using it also use the history....no idea.
> However the clean solution would be to migrate 5-10 history items, but not more.

Thanks for your feedback. I'll give it a try over the next couple of days and see, if it can be implemented reliably with reasonable effort.

**Comment by Lineflyer** [comment]
> Thanks for your feedback. I'll give it a try over the next couple of days and see, if it can be implemented reliably with reasonable effort.

If the effort is unreasonable or "dangerous" we might also just drop it. I think no one will save important coords in there.

**Comment by moving-bits** [comment]
> > IMHO only very few users use the current "Go to". If those using it also use the history....no idea.
> > However the clean solution would be to migrate 5-10 history items, but not more.
> 
> Thanks for your feedback. I'll give it a try over the next couple of days and see, if it can be implemented reliably with reasonable effort.

I've created PR #8063 which migrates the most recent history targets to UDC ZZ0 waypoints (up to 5).
If that PR is fine, we are ready to prepare a beta version IMHO.

**Comment by Lineflyer** [comment]
> I've created PR #8063 which migrates the most recent history targets to UDC ZZ0 waypoints (up to 5).
If that PR is fine, we are ready to prepare a beta version IMHO.

I merged that PR now. 
I will test the migration itself while (later on) smoke testing the beta version.

**Comment by Lineflyer** [comment]
I will merge branches and create a beta version from the (new merged) `release` branch tonight.
Please object if there is something missing or WIP from your side.

**Comment by Lineflyer** [comment]
FYI: Merge done! `release` is now even with `master` 
Will smoke test and push beta version (RC) tonight.

**Comment by moving-bits** [comment]
Setting "Do not merge / WIP" due to #8042 / #8067.

**Comment by moving-bits** [comment]
So everything we know of yet is merged to release branch - we're ready for a new smoke test...

**Comment by Lineflyer** [comment]
Smoke test passed this time :) 
Will push beta/RC now.

**Comment by Lineflyer** [comment]
2020.01.16-RC pushed

**Comment by bekuno** [comment]
I will update the crowdin strings on sunday.
Please wait for it.

**Comment by Lineflyer** [comment]
Due to the amount of portuguese beta users currently having the "english only problem" I will do another RC latest on the weekend.
Ideally we include ZZ0 migration outcome, but if not its also not tragic, we can do another beta upgrade later on.

**Comment by moving-bits** [comment]
> Ideally we include ZZ0 migration outcome, but if not its also not tragic, we can do another beta upgrade later on.

I'll try to do this on Friday evening.

**Comment by Lineflyer** [comment]
I smoke tested a new build RC version 2020.01.26-RC also explicitly testing the upgrade path from release version as well as from last RC version.LGTM.
I will publish a new beta version today.

**Comment by bekuno** [comment]
Since the last release (20191230) we now have changes in 381 Java files in the main/src/cgeo/geocaching tree. 
Are these changes all covered in our tests? 
At least there is no test case for the new InternalConnector.

**Comment by Lineflyer** [comment]
> Are these changes all covered in our tests?

Thats a good point. I guess not.
If someone is able and has time to create meaningful tests, this is always welcome.
During the last years these tests were always helpful to see problems in code changes as well as on website changes.

**Comment by rsudev** [comment]
Just FYI: Right now there is a lot of translation activity on Crowdin (I am unsure whether you get these notifications as well). I think those should be imported before publish, shouldn't they?
If need be could I facilitate that e.g. tomorrow.

**Comment by bekuno** [comment]
@rsudev Thanks to have a look at this.
I already uploaded the latest strings to crowdin and wait for the strings translation and validation. 
I planed to create the PR today.

**Comment by Lineflyer** [comment]
Now that branches are fixed, we could/should issue another RC. Is that OK, or maybe not because I might have missed some ongoing things in the last three weeks due to my vacation.

**Comment by moving-bits** [comment]
Nothing blocking that I know of, so if nothing's in support mail we can build an RC.

Only possible blocker may be #8126 - but that looks like an older regression already present in current release (see #7024), and seems not that easy to get a grip on.

**Comment by MagpieFourtyTwo** [comment]
> #8126 - but that looks like an older regression already present in current release

Don't think so - last release is dated 2019.12.30, but those crashes just happen since about a month or so. If the reason for the crashes would have been there before, I would have stumbled about it way earlier, for sure, cause they disrupt my normal c:geo use completely (as I usually have c:geo open while on the road, wiping around on the map, looking for reasonable reachable interesting caches).

**Comment by Lineflyer** [comment]
FYI:
I issued a new beta version 2020.02.24-RC after brief smoketest and test of fixes.

**Comment by moving-bits** [comment]
> FYI:
> I issued a new beta version 2020.02.24-RC after brief smoketest and test of fixes.

Thanks!

**Comment by Lineflyer** [comment]
Over the last days I used 2020.02.24-RC and especially tried to find out if #8126 is occuring with this version.
It seems the map is stable with this version.

So my plan would be to take a last look on the Play Store reports and then release this version for the public.
Any suggestion or missing changes?

**Comment by Lineflyer** [comment]
Addition: f4535ec is missing in this RC. @moving-bits : It should not be critical to include this into the release, what do you think?

**Comment by Lineflyer** [comment]
Preparing release now:

- [x] Check/Insert correct version name as headline in ```changelog-release.xml```
- [ ] Build release on CI server
- [ ] Perform smoke test with resulting ```cgeo-release.apk``` before continuing
- [ ] Upload and publish ```cgeo-release.apk``` to Google Play
- [ ] Tag the release on Github
- [ ] Publish the release on Github including upload of ```cgeo-release.apk``` to Github
- [ ] Publish release on F-Droid 
- [ ] Trigger notification to status.cgeo.org via CI server once the release is available on Google Play
- [ ] Post release info to Facebook 
- [ ] Post release info to Twitter

**Comment by Lineflyer** [comment]
OK, I included f4535ec into release and started the process.
Google is digesting the APK now. Will continue tonight.

**Comment by moving-bits** [comment]
@Lineflyer  Sorry, have been offline the whole weekend

> Addition: [f4535ec](https://github.com/cgeo/cgeo/commit/f4535ec00e3fe53bfa70f423ed1f54e0acd12f01) is missing in this RC. @moving-bits : It should not be critical to include this into the release, what do you think?

Yes, it should not be critical. But hasn't it already been included - see #8143?

**Comment by Lineflyer** [comment]
> Sorry, have been offline the whole weekend

No need to say sorry :)

> Yes, it should not be critical. But hasn't it already been included - see #8143?

It was on `release` but not in the RC version.
But meanwhile I just built a release and published it from HEAD of `release`, so its in.

BTW:
Release is done!

**Comment by moving-bits** [comment]
> It was on `release` but not in the RC version.
> But meanwhile I just built a release and published it from HEAD of `release`, so its in.

Ah, I see. (I had thought the RC was built after merging.)

> BTW:
> Release is done!

Thanks for preparing the release! Great to have a new version live.
I'd noticed it over the weekend, but for some reason my mobile did not download it and only finished when I arrived back home...
